name = "HierarchicalCompartmentModels"
uuid = "b51e7284-5176-45b4-bd61-9ca209d66691"
authors = ["James Bender"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
